# Generated by Django 5.0.4 on 2024-05-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_category_contract_contractrecipe_paymentmethod_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
