# Generated by Django 5.0.4 on 2024-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ExpenseUser',
        ),
    ]
